package View.Forms;

import Model.CardModel;
import javax.swing.ImageIcon;

public class HomeForm extends javax.swing.JPanel {

    public HomeForm() {
        initComponents();
         card1.setData(new CardModel(new ImageIcon(getClass().getResource("/Imgs/stock.png")), "Stock Total", "200,000", "Aumento 10%"));
        card2.setData(new CardModel(new ImageIcon(getClass().getResource("/Imgs/profit.png")), "Usuários", "5,000", "Aumento 39%"));
        card3.setData(new CardModel(new ImageIcon(getClass().getResource("/Imgs/flag.png")), "Saídas", "100", "Aumento 20%"));
        //  add row table
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCards = new javax.swing.JLayeredPane();
        card1 = new View.Components.Card();
        card2 = new View.Components.Card();
        card3 = new View.Components.Card();

        setBackground(new java.awt.Color(220, 220, 220));
        setPreferredSize(null);

        pnCards.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        card1.setColor1(new java.awt.Color(142, 142, 250));
        card1.setColor2(new java.awt.Color(123, 123, 245));
        pnCards.add(card1);

        card2.setColor1(new java.awt.Color(186, 123, 247));
        card2.setColor2(new java.awt.Color(167, 94, 236));
        pnCards.add(card2);

        card3.setColor1(new java.awt.Color(241, 208, 62));
        card3.setColor2(new java.awt.Color(211, 184, 61));
        pnCards.add(card3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnCards, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnCards, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.Components.Card card1;
    private View.Components.Card card2;
    private View.Components.Card card3;
    private javax.swing.JLayeredPane pnCards;
    // End of variables declaration//GEN-END:variables
}
